spring.application.name=kata
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}


# Set to false to completely bypass Spring Security filter chains
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
