spring.application.name=kata
spring.jpa.hibernate.ddl-auto=update

# Set to false to completely bypass Spring Security filter chains
spring.autoconfigure.exclude=\
org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,\
org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

spring.jpa.defer-datasource-initialization=true
# allowing only for h2 case
spring.sql.init.mode=embedded
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:bookstore
#; DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=